/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TickerImport } from './routes/ticker'
import { Route as PortfolioImport } from './routes/portfolio'
import { Route as FundamentalsImport } from './routes/fundamentals'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TickerRoute = TickerImport.update({
  id: '/ticker',
  path: '/ticker',
  getParentRoute: () => rootRoute,
} as any)

const PortfolioRoute = PortfolioImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRoute,
} as any)

const FundamentalsRoute = FundamentalsImport.update({
  id: '/fundamentals',
  path: '/fundamentals',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fundamentals': {
      id: '/fundamentals'
      path: '/fundamentals'
      fullPath: '/fundamentals'
      preLoaderRoute: typeof FundamentalsImport
      parentRoute: typeof rootRoute
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioImport
      parentRoute: typeof rootRoute
    }
    '/ticker': {
      id: '/ticker'
      path: '/ticker'
      fullPath: '/ticker'
      preLoaderRoute: typeof TickerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fundamentals': typeof FundamentalsRoute
  '/portfolio': typeof PortfolioRoute
  '/ticker': typeof TickerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fundamentals': typeof FundamentalsRoute
  '/portfolio': typeof PortfolioRoute
  '/ticker': typeof TickerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/fundamentals': typeof FundamentalsRoute
  '/portfolio': typeof PortfolioRoute
  '/ticker': typeof TickerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fundamentals' | '/portfolio' | '/ticker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fundamentals' | '/portfolio' | '/ticker'
  id: '__root__' | '/' | '/fundamentals' | '/portfolio' | '/ticker'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FundamentalsRoute: typeof FundamentalsRoute
  PortfolioRoute: typeof PortfolioRoute
  TickerRoute: typeof TickerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FundamentalsRoute: FundamentalsRoute,
  PortfolioRoute: PortfolioRoute,
  TickerRoute: TickerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fundamentals",
        "/portfolio",
        "/ticker"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/fundamentals": {
      "filePath": "fundamentals.tsx"
    },
    "/portfolio": {
      "filePath": "portfolio.tsx"
    },
    "/ticker": {
      "filePath": "ticker.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
